### ISSUE TITLE
记录 bug 一枚

### ISSUE THREAD

**Issue by xiangshouding** [fex-team/fis-kernel#15]
*project.js*
```js
exports.getSource = function () {
  //...
}
```
这个流程里面，当文件 `release: false` 时过滤源码，理论上来说这样的设定也对，因为都不产出了还编译个毛线；

但是在 watch 的时候没有把这些文件 exclude 掉，这时候就有可能会由于种种原因跟不 watch 时编译不一致；

**Comment by puppywang** [comment]
大神看看这么改可以么? 我们把fis目录当成一个代码仓库了, proto目录下面很多文件都是开发原型, 通过制定release: false来忽略编辑, 但是最近的版本使用-w参数启用watch功能后, 这些无用的文件又会编译, 让费了好多时间.

**Comment by puppywang** [comment]
https://github.com/fex-team/fis-command-release/pull/15

**Comment by xiangshouding** [comment]
fix 2532c9d7627beb9ee6e9656535080ae98658c6db
